# Generated by Django 4.2.4 on 2023-09-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(1, 'Hoạt động'), (0, 'Không hoạt động')], default=1),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Hoạt động'), (0, 'Không hoạt động')], default=1),
        ),
        migrations.AlterField(
            model_name='termsandservices',
            name='status',
            field=models.IntegerField(choices=[(1, 'Hoạt động'), (0, 'Không hoạt động')], default=1),
        ),
    ]
