# Generated by Django 4.2.4 on 2023-10-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_related_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
