# Generated by Django 4.2.4 on 2023-10-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_uploadedimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='view',
            new_name='viewed',
        ),
    ]
